#!/usr/bin/env bash
# Registers tether as a systemd service for the current user.
#
# Usage:
#   deploy/install-systemd.sh [install|uninstall|status] [--dry-run] [--yes]
#
#   install    (default) write /etc/systemd/system/tether.service, stop a manually
#              started tether if any, then enable and start the service
#   uninstall  stop and disable the service and remove the unit file
#   status     show the service status
#   --dry-run  print what would be done (including the unit file) without changing anything
#   --yes      do not ask before stopping a running tether
#
# Run it as your normal user; it calls sudo only for the privileged steps.
set -euo pipefail

ACTION="install"
DRY_RUN=0
ASSUME_YES=0
for arg in "$@"; do
  case "$arg" in
    install | uninstall | status) ACTION="$arg" ;;
    --dry-run) DRY_RUN=1 ;;
    --yes | -y) ASSUME_YES=1 ;;
    -h | --help)
      sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "unknown argument: $arg (see --help)" >&2
      exit 2
      ;;
  esac
done

SERVICE="tether"
UNIT_PATH="/etc/systemd/system/${SERVICE}.service"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN="${REPO_DIR}/bin/tether"
RUN_USER="${SUDO_USER:-$(id -un)}"
RUN_GROUP="$(id -gn "$RUN_USER")"
RUN_HOME="$(getent passwd "$RUN_USER" | cut -d: -f6)"
ENV_FILE="${RUN_HOME}/.config/tether/env"

info() { printf '==> %s\n' "$*"; }
warn() { printf 'warning: %s\n' "$*" >&2; }
die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

# run executes a command, or only prints it with --dry-run.
run() {
  if [ "$DRY_RUN" -eq 1 ]; then
    printf '[dry-run] %s\n' "$*"
  else
    "$@"
  fi
}

# env_value prints the value of KEY from the env file (empty if unset).
env_value() {
  [ -f "$ENV_FILE" ] || return 0
  grep -E "^$1=" "$ENV_FILE" | tail -n1 | cut -d= -f2- || true
}

render_unit() {
  cat <<EOF
# Generated by deploy/install-systemd.sh. Edit settings in ${ENV_FILE}, not here.
[Unit]
Description=tether (Claude Code web UI)
After=network-online.target tailscaled.service
Wants=network-online.target

[Service]
Type=simple
User=${RUN_USER}
Group=${RUN_GROUP}
WorkingDirectory=${RUN_HOME}
EnvironmentFile=-${ENV_FILE}
# A login shell gives Claude Code the same PATH (go, ~/.local/bin, ...) as an interactive terminal.
ExecStart=/bin/bash -lc 'exec ${BIN} serve'
Restart=on-failure
RestartSec=3
# tether stops its sessions itself on SIGTERM; conversations are resumed on next start.
KillMode=mixed
TimeoutStopSec=20
SyslogIdentifier=${SERVICE}

[Install]
WantedBy=multi-user.target
EOF
}

# manual_pids lists tether servers of RUN_USER that systemd does not manage.
manual_pids() {
  local pid
  for pid in $(pgrep -u "$RUN_USER" -x tether || true); do
    if ! grep -q "${SERVICE}.service" "/proc/${pid}/cgroup" 2>/dev/null; then
      echo "$pid"
    fi
  done
}

# ensure_tailscale_host adds this machine's Tailscale DNS name to TETHER_HOSTS.
# tether also detects it at startup, but at boot tailscale may not be up yet, and
# without the name HTTPS requests via tailscale serve would be rejected (421).
ensure_tailscale_host() {
  command -v tailscale >/dev/null 2>&1 || return 0
  local name hosts
  name="$(tailscale status --self --json 2>/dev/null | sed -n 's/.*"DNSName": *"\([^"]*\)\.".*/\1/p' | head -n1)"
  [ -n "$name" ] || return 0
  hosts="$(env_value TETHER_HOSTS)"
  case ",${hosts}," in
    *",${name},"*) return 0 ;;
  esac
  info "adding ${name} to TETHER_HOSTS in ${ENV_FILE}"
  if [ "$DRY_RUN" -eq 1 ]; then
    printf '[dry-run] set TETHER_HOSTS=%s\n' "${hosts:+${hosts},}${name}"
    return 0
  fi
  if grep -qE '^TETHER_HOSTS=' "$ENV_FILE"; then
    sed -i "s|^TETHER_HOSTS=.*|TETHER_HOSTS=${hosts:+${hosts},}${name}|" "$ENV_FILE"
  else
    printf 'TETHER_HOSTS=%s\n' "$name" >>"$ENV_FILE"
  fi
}

# health_check succeeds when tether answers on TETHER_ADDR (TCP port or unix:<path>).
health_check() {
  local addr port
  addr="$(env_value TETHER_ADDR)"
  case "$addr" in
    unix:*) curl -sf --unix-socket "${addr#unix:}" http://localhost/api/health >/dev/null 2>&1 ;;
    *)
      port="${addr##*:}"
      curl -sf "http://127.0.0.1:${port:-3100}/api/health" >/dev/null 2>&1
      ;;
  esac
}

do_install() {
  [ -x "$BIN" ] || die "${BIN} not found; run 'make build' first"
  [ "$(id -u)" -ne 0 ] || [ -n "${SUDO_USER:-}" ] || die "run as your normal user (sudo is used only where needed)"

  if [ ! -f "$ENV_FILE" ]; then
    info "creating ${ENV_FILE}"
    run mkdir -p "$(dirname "$ENV_FILE")"
    if [ "$DRY_RUN" -eq 0 ]; then
      (umask 077 && printf '# tether settings (see README)\nTETHER_ADDR=127.0.0.1:3100\n' >"$ENV_FILE")
    fi
  fi

  local tmp
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' RETURN
  render_unit >"$tmp"
  if command -v systemd-analyze >/dev/null 2>&1; then
    # 検証用に一時ファイル名をサービス名に合わせる（systemd-analyzeはファイル名から種類を判断するため）
    local check_dir
    check_dir="$(mktemp -d)"
    cp "$tmp" "${check_dir}/${SERVICE}.service"
    local report
    # verifyはシステム上の他のunitも読み込み、その警告も出すので、このunitに関する行だけを見る
    report="$(systemd-analyze verify "${check_dir}/${SERVICE}.service" 2>&1 | grep -F "${check_dir}" || true)"
    if [ -z "$report" ]; then
      info "unit file verified"
    else
      warn "systemd-analyze reported:"
      printf '%s\n' "$report" >&2
    fi
    rm -rf "$check_dir"
  fi
  if [ "$DRY_RUN" -eq 1 ]; then
    info "unit file that would be written to ${UNIT_PATH}:"
    cat "$tmp"
  fi

  local pids
  pids="$(manual_pids)"
  if [ -n "$pids" ]; then
    local children
    children="$(for p in $pids; do pgrep -P "$p" || true; done | wc -l)"
    warn "tether is running outside systemd (pid ${pids//$'\n'/ }, ${children} session process(es))."
    warn "stopping it ends running terminals; Claude Code conversations can be resumed afterwards."
    if [ "$ASSUME_YES" -eq 0 ] && [ "$DRY_RUN" -eq 0 ]; then
      read -r -p "stop it and continue? [y/N] " answer
      case "$answer" in
        y | Y | yes) ;;
        *) die "aborted" ;;
      esac
    fi
    info "stopping manually started tether"
    # shellcheck disable=SC2086
    run kill $pids
    if [ "$DRY_RUN" -eq 0 ]; then
      for _ in $(seq 1 80); do
        [ -z "$(manual_pids)" ] && break
        sleep 0.25
      done
      [ -z "$(manual_pids)" ] || die "tether did not stop"
    fi
  fi

  # 設定ファイルの変更は、止める確認に同意してもらった後に行う（中止したときに何も変わらないように）
  ensure_tailscale_host
  info "installing ${UNIT_PATH}"
  run sudo install -m 644 "$tmp" "$UNIT_PATH"
  run sudo systemctl daemon-reload
  run sudo systemctl enable "$SERVICE"
  run sudo systemctl restart "$SERVICE"

  if [ "$DRY_RUN" -eq 1 ]; then
    info "dry run finished; nothing was changed"
    return 0
  fi
  for _ in $(seq 1 40); do
    if health_check; then
      info "tether is up ($(env_value TETHER_ADDR))"
      systemctl --no-pager --lines=5 status "$SERVICE" || true
      info "logs: journalctl -u ${SERVICE} -f"
      return 0
    fi
    sleep 0.5
  done
  systemctl --no-pager --lines=20 status "$SERVICE" || true
  die "tether did not become healthy; check: journalctl -u ${SERVICE} -e"
}

do_uninstall() {
  info "stopping and disabling ${SERVICE}"
  run sudo systemctl disable --now "$SERVICE" || true
  if [ -f "$UNIT_PATH" ]; then
    run sudo rm -f "$UNIT_PATH"
  fi
  run sudo systemctl daemon-reload
  info "done (settings in ${ENV_FILE} and data in ~/.local/share/tether are kept)"
}

case "$ACTION" in
  install) do_install ;;
  uninstall) do_uninstall ;;
  status) systemctl --no-pager status "$SERVICE" ;;
esac
